name: project_server
version: 1.0.0
description: A new Get Server application.
environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  get_server: 1.2.1
  mysql1: ^0.20.0
  jaguar_jwt: 3.0.0
  crypto: ^3.0.3

dev_dependencies:
  lints: ^2.1.1
  test: 1.24.4
